### ISSUE TITLE
Links to specific sections of carbonplan.org/research do not resolve to that section

### ISSUE THREAD

**Issue by badgley** [carbonplan/research#240]
I would like to share a link to CarbonPlan's [publications](https://carbonplan.org/research?section=publications). 

# Expected behavior
I would expect the link `https://carbonplan.org/research?section=publications` to take me to the `Publications` section of the research page. 

# What actually happens
The above links don't actually take me to the relevant section. Instead, I'm taken to the top of the page. This means that the following links all lead to the same place: 

- https://carbonplan.org/research?section=publications
- https://carbonplan.org/research
- https://carbonplan.org/research?section=tools

## Environment
Looks like this behavior occurs across browsers, including Chrome, Firefox, and Safari.

**Comment by katamartin** [comment]
It looks like this behavior is in place to accommodate respecting the default page position on browser navigation -- i.e. if you scroll down to click on an article then navigate back to `carbonplan.org/research`, your position on the page should be preserved regardless of whichever section you last clicked on.

This is is the logic that's currently used:
https://github.com/carbonplan/research/blob/4a69763525046636ccc81624c01df1fdd569e408/pages/_app.js#L13-L18
https://github.com/carbonplan/research/blob/4a69763525046636ccc81624c01df1fdd569e408/components/main.js#L65

I'll look into whether we can tweak into something that more specifically targets the browser back button.
